spring:
  profiles:
    active: @activeProfile@
  datasource:
    url: jdbc:h2:mem:hexagonal
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs