CREATE TABLE ITEM_SEQ_LOCK (id INT PRIMARY KEY);
INSERT INTO ITEM_SEQ_LOCK(id) VALUES (1);
INSERT INTO ITEM (ID, NAME) VALUES
     (1, 'Item A'),
     (2, 'Item B'),
     (3, 'Item C');
ALTER SEQUENCE ITEM_SEQ RESTART WITH (SELECT MAX(id) + 1 FROM item);